# Introduction

Table of contents:

- [Numpy](#numpy)
  - [Arrays](#numpy-arrays)
  - [Slicing](#numpy-array-slicing)
  - [Array math](#numpy-math)
  - [Broadcasting](#numpy-broadcasting)
- [Matplotlib](#matplotlib)
  - [Plotting](#matplotlib-plotting)
  - [Subplots](#matplotlib-subplots)
  - [Images](#matplotlib-images)
- [Pandas](#pandas)

In [1]:
# common header
%matplotlib inline

<a name='numpy'></a>
# Numpy

[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python. 
It provides a high-performance multidimensional array object and tools for working with these arrays.

<a name='numpy-arrays'></a>

### Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the *rank* of the array; the *shape* of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array can be created using Python list:

In [2]:
import numpy as np

a = np.array([1, 2, 3])  # rank 1 array
a

array([1, 2, 3])

In [3]:
a[0]  # access array element

1

In [4]:
type(a)  # prints array type

numpy.ndarray

In [5]:
a.shape  # prints array shape e.g. size of array according to each dimensions

(3,)

Numpy also provides other functions to create arrays for different use cases:

In [6]:
np.zeros((2, 3))  # 2 by 3 array of 0

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
np.ones((2, 3))  # 2 by 3 array of 1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
np.random.random((2, 3))  # 2 by 3 array filled with random values

array([[ 0.1090407 ,  0.79436302,  0.95772478],
       [ 0.1566768 ,  0.24175988,  0.319846  ]])

Of course there is more information to read about other methods of array creation [in the documentation](http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

<a name='numpy-array-slicing'></a>

### Array slicing

Similar to Python lists, numpy arrays can be sliced.
Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Slicing can be used to pull out the subarray consisting of the first 2 rows and columns 1 and 2 (excluding); b is the following array of shape (2, 2):

In [10]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [11]:
a[:, 1]  # get the second column

array([ 2,  6, 10])

In [12]:
a[1, :]  # get the second row

array([5, 6, 7, 8])

In [13]:
a[[0, 0, 0]]  # create 3 by 4 array from original one

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
a > 4  # finds elements bigger than 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [15]:
a[(a > 4)]  # select values bigger than 4

array([ 5,  6,  7,  8,  9, 10, 11, 12])

For more details [read the documentation](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

<a name='numpy-math'></a>

### Array math

TODO

<a name='numpy-broadcasting'></a>

### Broadcasting

TODO

<a name='matplotlib'></a>

# Matplotlib

TODO

<a name='matplotlib-plotting'></a>

### Plotting

TODO

<a name='matplotlib-subplots'></a>

### Subplots

TODO

<a name='matplotlib-images'></a>

### Images

TODO

<a name='pandas'></a>

# Pandas

TODO