# Introduction [NumPy](http://www.numpy.org/)

In this section we're going to explore some of the fundamental concepts and usage of [NumPy](http://www.numpy.org/) to perform linear algebra computation.

Table of contents:

- [Numpy](#numpy)
  - [Arrays](#numpy-arrays)
  - [Slicing](#numpy-array-slicing)
  - [Array math](#numpy-math)
  - [Broadcasting](#numpy-broadcasting)

# Numpy

<a name='numpy'></a>

[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python. 
It provides a high-performance multidimensional array object and tools for working with these arrays.

<a name='numpy-arrays'></a>
### Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the *rank* of the array; the *shape* of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array can be created using Python list:

In [1]:
import numpy as np

a = np.array([1, 2, 3])  # rank 1 array
a

array([1, 2, 3])

In [2]:
a[0]  # access array element

1

In [3]:
type(a)  # prints array type

numpy.ndarray

In [4]:
a.shape  # prints array shape e.g. size of array according to each dimensions

(3,)

There is also possible to get information about number of array dimensions

In [5]:
np.array([[1], [2], [3]]).ndim

2

Numpy also provides other functions to create arrays for different use cases:

In [6]:
np.zeros((2, 3))  # 2 by 3 array of 0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2, 3))  # 2 by 3 array of 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.random.random((2, 3))  # 2 by 3 array filled with random values

array([[0.45007466, 0.20104012, 0.64184405],
       [0.98984172, 0.31399078, 0.12601408]])

Of course there is more information to read about other methods of array creation [in the documentation](http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

<a name='numpy-array-slicing'></a>

### Array slicing

Similar to Python lists, numpy arrays can be sliced.
Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Slicing can be used to pull out the subarray consisting of the first 2 rows and columns 1 and 2 (excluding); b is the following array of shape (2, 2):

In [10]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [11]:
a[:, 1]  # get the second column

array([ 2,  6, 10])

In [12]:
a[1, :]  # get the second row

array([5, 6, 7, 8])

In [13]:
a[[0, 0, 0]]  # create 3 by 4 array from original one

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
a > 4  # finds elements bigger than 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
a[(a > 4)]  # select values bigger than 4

array([ 5,  6,  7,  8,  9, 10, 11, 12])

Sometimes we need to transform given array shape into something else

In [16]:
np.random.random((2, 3)).reshape((3,2))

array([[0.82800611, 0.61766695],
       [0.79163738, 0.10382213],
       [0.49353792, 0.25956628]])

In [17]:
np.random.random((2, 3)).T

array([[0.31899797, 0.68827506],
       [0.0610689 , 0.18676849],
       [0.30125526, 0.6380273 ]])

Another case when 

For more details [read the documentation](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

<a name='numpy-math'></a>

### Array math

In [18]:
arr = np.arange(3)
print(arr)

[0 1 2]


Exponenta

In [19]:
np.exp(arr)

array([1.        , 2.71828183, 7.3890561 ])

SQRT

In [20]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356])

Sum

In [21]:
np.add(np.array([2, 3, 4]), arr)

array([2, 4, 6])

Dot product

In [22]:
np.dot(arr, np.ones(3,))

3.0

<a name='numpy-broadcasting'></a>

### Broadcasting

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. 
Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example

In [23]:
a = np.array([1., 2., 3.])
print(a)

b = np.array([2., 2., 2.])
print(b)

a * b

[1. 2. 3.]
[2. 2. 2.]


array([2., 4., 6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation

In [24]:
a = np.array([1., 2., 3.])
b = 2.
a * b

array([2., 4., 6.])

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

- they are equal, or
- one of them is 1

If these conditions are not met, a `ValueError` frames are not aligned exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

In [25]:
rgb = np.random.random((256, 256, 3))
rgb

array([[[0.12283024, 0.80566473, 0.37066373],
        [0.65888086, 0.05567102, 0.87048391],
        [0.27082061, 0.94167922, 0.8423388 ],
        ...,
        [0.76750355, 0.58032218, 0.55725788],
        [0.47588755, 0.76242072, 0.66288255],
        [0.10436032, 0.58771783, 0.58169964]],

       [[0.11305162, 0.90965728, 0.20283836],
        [0.11513393, 0.93640617, 0.05433866],
        [0.01531808, 0.67877822, 0.77673024],
        ...,
        [0.15321342, 0.36750917, 0.07156451],
        [0.95117095, 0.81747382, 0.13103572],
        [0.28835803, 0.14596633, 0.34580967]],

       [[0.82601454, 0.3712809 , 0.13286399],
        [0.17456923, 0.16077268, 0.34735136],
        [0.60696298, 0.68948211, 0.06427159],
        ...,
        [0.30190525, 0.05878598, 0.42736932],
        [0.61965135, 0.13859323, 0.93796633],
        [0.58976347, 0.97608595, 0.86450066]],

       ...,

       [[0.27097719, 0.86496864, 0.05771362],
        [0.18954677, 0.68817929, 0.10675535],
        [0.4934071 , 0

In [26]:
scale = np.zeros(3)
scale

array([0., 0., 0.])

In [27]:
rgb * scale

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.array([1,2,3]) * np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 