# Introduction [NumPy](http://www.numpy.org/)

In this section we're going to explore some of the fundamental concepts and usage of [NumPy](http://www.numpy.org/) to perform linear algebra computation.

Table of contents:

- [Numpy](#numpy)
  - [Arrays](#numpy-arrays)
  - [Slicing](#numpy-array-slicing)
  - [Array math](#numpy-math)
  - [Broadcasting](#numpy-broadcasting)

# Numpy

<a name='numpy'></a>

[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python. 
It provides a high-performance multidimensional array object and tools for working with these arrays.

<a name='numpy-arrays'></a>
### Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the *rank* of the array; the *shape* of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array can be created using Python list:

In [1]:
import numpy as np

a = np.array([1, 2, 3])  # rank 1 array
a

array([1, 2, 3])

In [2]:
a[0]  # access array element

1

In [3]:
type(a)  # prints array type

numpy.ndarray

In [4]:
a.shape  # prints array shape e.g. size of array according to each dimensions

(3,)

There is also possible to get information about number of array dimensions

In [5]:
np.array([[1], [2], [3]]).ndim

2

Numpy also provides other functions to create arrays for different use cases:

In [6]:
np.zeros((2, 3))  # 2 by 3 array of 0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2, 3))  # 2 by 3 array of 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.random.random((2, 3))  # 2 by 3 array filled with random values

array([[0.52097627, 0.48368031, 0.66632389],
       [0.29674657, 0.81936256, 0.89682934]])

Of course there is more information to read about other methods of array creation [in the documentation](http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

<a name='numpy-array-slicing'></a>

### Array slicing

Similar to Python lists, numpy arrays can be sliced.
Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Slicing can be used to pull out the subarray consisting of the first 2 rows and columns 1 and 2 (excluding); b is the following array of shape (2, 2):

In [10]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [11]:
a[:, 1]  # get the second column

array([ 2,  6, 10])

In [12]:
a[1, :]  # get the second row

array([5, 6, 7, 8])

In [13]:
a[[0, 0, 0]]  # create 3 by 4 array from original one

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
a > 4  # finds elements bigger than 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
a[(a > 4)]  # select values bigger than 4

array([ 5,  6,  7,  8,  9, 10, 11, 12])

Sometimes we need to transform given array shape into something else

In [16]:
np.random.random((2, 3)).reshape((3,2))

array([[0.13839812, 0.7594451 ],
       [0.01805907, 0.69986031],
       [0.16544196, 0.83934624]])

In [17]:
np.random.random((2, 3)).T

array([[0.89834496, 0.47733117],
       [0.31759173, 0.42278795],
       [0.27302162, 0.55590502]])

For more details [read the documentation](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

<a name='numpy-math'></a>

### NumPy and Linear Algebra

- **Scalars**: A single number

In [18]:
scalar = 13
scalar

13

- **Vector**: A 1D array of numbers, where each element is identified by a single index

In [19]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

- **Matrix**: A 2D array of numbers. In matrices a single element is identified by two indexes e.g. row and column.

In [20]:
matrix = np.random.random((3, 4))
matrix

array([[0.18431612, 0.87119921, 0.0262641 , 0.13838085],
       [0.22605083, 0.72326991, 0.7102001 , 0.66043532],
       [0.7024839 , 0.98409633, 0.5769516 , 0.95114713]])

- **Tensor**: An ND array of numbers.

In [21]:
tensor = np.random.random((3, 4, 2))
tensor

array([[[0.68045831, 0.23495256],
        [0.06996894, 0.68988542],
        [0.4869466 , 0.39986468],
        [0.72514639, 0.05838651]],

       [[0.85388137, 0.1034624 ],
        [0.51262743, 0.01438068],
        [0.76401217, 0.23751307],
        [0.95651627, 0.57517809]],

       [[0.14789581, 0.57284059],
        [0.88950349, 0.10318754],
        [0.51876401, 0.18368744],
        [0.9828295 , 0.44763537]]])

In [22]:
arr = np.arange(3)
print(arr)

[0 1 2]


Matrix multiplication by **scalar**

In [23]:
2 * np.ones((2, 3))

array([[2., 2., 2.],
       [2., 2., 2.]])

Matrix addition/subtraction

In [24]:
np.array([1, 2, 3]) + np.ones((1, 3))

array([[2., 3., 4.]])

In [25]:
np.array([2, 3, 4]) - np.ones((1, 3))

array([[1., 2., 3.]])

Matrix multiplication.

The matrix product of an $n×m$ matrix with an $m×ℓ$ matrix is an $n×ℓ$ matrix. The $(i,j)$ entry of the matrix product $AB$ is the dot product of the $ith$ row of $A$ with the $jth$ column of $B$.

The number of columns in the first matrix must match the number of rows in the second matrix. The result will be another matrix or a scalar with dimensions defined by the rows of the first matrix and columns of the second matrix.

![Matrix multiplication](/notebooks/assets/img/matrix-multiplication-diagram.png)

In [26]:
np.dot(np.array([[1, 2, 3], [1, 2, 3]]), np.ones((3, 2)))

array([[6., 6.],
       [6., 6.]])

Exponenta

In [27]:
np.exp(arr)

array([1.        , 2.71828183, 7.3890561 ])

SQRT

In [28]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356])

Mean of values across some dimension

In [29]:
rnd = np.random.random((3, 7))
print(rnd)
np.mean(rnd, axis=0)

[[0.00397757 0.71792866 0.73420738 0.33350027 0.95111442 0.6039766
  0.06368186]
 [0.44068596 0.18390706 0.08910923 0.95650203 0.8024918  0.15021102
  0.19072152]
 [0.97902316 0.07464001 0.11270269 0.66690704 0.03356954 0.99763067
  0.90507479]]


array([0.47456223, 0.32549191, 0.31200643, 0.65230311, 0.59572525,
       0.58393943, 0.38649272])

For more information on the other functions available in [go here](https://docs.scipy.org/doc/numpy/reference/routines.html)

<a name='numpy-broadcasting'></a>

### Broadcasting

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. 
Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example

In [30]:
a = np.array([1., 2., 3.])
print(a)

b = np.array([2., 2., 2.])
print(b)

a * b

[1. 2. 3.]
[2. 2. 2.]


array([2., 4., 6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation

In [31]:
a = np.array([1., 2., 3.])
b = 2.
a * b

array([2., 4., 6.])

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

- they are equal, or
- one of them is 1

If these conditions are not met, a `ValueError` frames are not aligned exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

In [32]:
rgb = np.random.random((256, 256, 3))
rgb

array([[[6.56625453e-01, 9.17770148e-01, 5.96020632e-01],
        [6.23274398e-01, 7.60972166e-01, 7.17815412e-01],
        [7.81231695e-01, 5.01446366e-01, 2.44149708e-01],
        ...,
        [9.26351353e-01, 1.59256306e-01, 8.35326738e-01],
        [7.25176419e-04, 3.21808441e-01, 8.40152654e-02],
        [1.85964499e-01, 5.91785427e-01, 8.51403125e-01]],

       [[3.79242469e-01, 5.35776862e-01, 2.26676045e-01],
        [2.64060590e-01, 4.99099889e-01, 8.72261206e-01],
        [5.23502054e-01, 4.31131381e-01, 2.16106348e-02],
        ...,
        [6.92340049e-01, 4.79133498e-01, 3.00942106e-01],
        [3.27698274e-01, 4.00583674e-01, 8.31498333e-02],
        [3.50284253e-01, 2.56265460e-01, 9.45571141e-01]],

       [[6.59500218e-01, 9.77680457e-01, 7.49053219e-01],
        [4.38519693e-01, 3.43903710e-01, 4.57312153e-01],
        [3.23120176e-01, 1.56129515e-01, 4.84084388e-01],
        ...,
        [6.19457448e-01, 7.10901120e-01, 6.86413459e-01],
        [2.06515899e-01, 6.80

In [33]:
scale = np.zeros(3)
scale

array([0., 0., 0.])

In [34]:
rgb * scale

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
np.array([1,2,3]) * np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 